spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
    locations: classpath:/migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    default-schema: bandhub
    out-of-order: true
    ignore-migration-patterns: '*:ignored'
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/jd2project"
      maximum-pool-size: 10
      driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: "jdbc:postgresql://localhost:5432/jd2project"
server:
  port: 8080

---

jwt:
  secret: nieh89*Ujj_00098kniu>
  expiration: 60000

